language: python
python:
  - "2.7"

cache: pip

addons:
  apt:
    packages:
    - gfortran

install:
  - python setup.py config_fc --fcompiler=gnu95 --opt="-Ofast" --f90flags="-cpp -fopenmp -march=native" build install

script: nosetests -w tests/unit_tests

after_success:
  - coveralls