language: python
python:
  - "3.7.4"

cache: pip

addons:
  apt:
    packages:
    - gfortran
    - python-pip
    - libeigen3-dev
    - python-scipy

before_install:
  - pip install astropy pybind11 george

install:
  - python setup.py install

script: nosetests -w tests/unit_tests

after_success:
  - coveralls 