language: python
python:
  - "3.7"

cache: pip

addons:
  apt:
    packages:
    - gfortran
    - python-pip
    - libeigen3-dev
    - python-numpy
    - python-scipy

before_install:
  - pip install george

install:
  - python setup.py install

script: nosetests -w tests/unit_tests

after_success:
  - coveralls 